### ISSUE TITLE
Change default comment color

### ISSUE THREAD

**Issue by robamu** [15knots/cmakeed#17]
Hi,

Just a small improvement suggestion: What do you think about changing the default color for strings:

 ![defaultColor](https://user-images.githubusercontent.com/31589589/115847960-b278bd80-a423-11eb-9d29-cd41d8ea580e.png)

The dark blue is hard to read in dark modes and I think the brighter color is good to read for both
light mode and dark mode users. Its the bright blue from the top row in the color selector

Kind Regards
Robin

**Comment by patrickcrouch** [comment]
Tbh all the colors could be a bit brighter in dark mode.  Maybe add a theme switch like in General>Appearances?  For now, I threw all the colors in a picker and lightened them, and came up with this (might save you a little trouble):
CMake Defined Variables #c5c584
CMake Properties #00bc7d
Commands #0091f7
Comments #00c900
Deprecated Commands #0091f7
Referenced Variables #518bc9
Reserved Words #c88686
Strings #9280ff
User Defined Variables #5693d5

Otherwise, love this plugin!  Thanks!

**Comment by 15knots** [comment]
@patrickcrouch I added an improved dark color theme. Since I do not use any dark color themes, you might wish to review/test mine before it gets released.
It is located at [e4-cmakeed_dark.css](https://github.com/15knots/cmakeed/blob/master/com.cthing.cmakeed.ui/css/e4-cmakeed_dark.css)
