### ISSUE TITLE
Insecure unsigned setup vulnerable for MIM attack

### ISSUE THREAD

**Issue by skryv-softserveinc** [15knots/cmakeed#5]
<img width="391" alt="screen shot 2018-04-16 at 12 15 06 pm" src="https://user-images.githubusercontent.com/32171051/38800458-fe768542-416f-11e8-80d8-eed625b9fb00.png">

**Comment by 15knots** [comment]
The dialog is shown for every plugin that has unsigned jars. CMake does not sign its jars due to a lack of certificate and due to the fact that it would not be feasible to store a jar signing key on on travis-ci, where the plugin is build.

Anyway, the download site at https://dl.bintray.com/15knots/p2-zip/ is TLS protected, so how does that constitute a MIM vulnerability?

**Comment by skryv-softserveinc** [comment]
I guess, yes. But CDT project signs its plugins for example. This would be an extra layer of security to be sure its built by yours and not patched on a server. You may want to consider to take a look onto CDT to see how they solve this for their make plugin.

**Comment by 15knots** [comment]
I'm aware of the jar-signing maven plugin used by eclipse. Unfortunately,
it is only available if the build is run at eclipse.org.
CMakeEd is build from pristine sources by travis-ci.org org and uploaded to
bintray.

2018-04-17 10:32 GMT+02:00 skryv-softserveinc <notifications@github.com>:
